package ArbolAVLGUI;

import java.awt.BorderLayout;
import java.awt.Rectangle;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenin Sanchez
 */
public class Gui extends javax.swing.JFrame {
    
    private SimuladorAB simulador = new SimuladorAB();

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        this.setTitle("ARBOL AVL GRAFICO");
        this.setLocationRelativeTo(null);
    }
    
    private void inicializar(boolean enable) {
        this.jbnInsertar.setEnabled(enable);        
        this.jbnBuscar.setEnabled(enable);
        this.jbnEliminar.setEnabled(enable);
        this.jbnPreOrden.setEnabled(enable);
        this.jbnPostOrden.setEnabled(enable);        
        this.jbnInOrden.setEnabled(enable);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatos = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jbnInsertar = new javax.swing.JButton();
        jbnBuscar = new javax.swing.JButton();
        jbnEliminar = new javax.swing.JButton();
        jbnPreOrden = new javax.swing.JButton();
        jbnInOrden = new javax.swing.JButton();
        jbnPostOrden = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        jtaDatos.setEditable(false);
        jtaDatos.setBackground(new java.awt.Color(204, 204, 204));
        jtaDatos.setColumns(20);
        jtaDatos.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jtaDatos.setForeground(new java.awt.Color(102, 102, 102));
        jtaDatos.setRows(5);
        jtaDatos.setBorder(null);
        jScrollPane1.setViewportView(jtaDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 0, 220, 280));

        jDesktopPane1.setBackground(new java.awt.Color(255, 102, 0));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setOpaque(false);

        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setEnabled(false);
        jInternalFrame2.setFocusCycleRoot(false);
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jInternalFrame2);
        jInternalFrame2.setBounds(10, 10, 430, 270);

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 450, 290));

        jbnInsertar.setBackground(new java.awt.Color(204, 204, 204));
        jbnInsertar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnInsertar.setForeground(new java.awt.Color(51, 51, 51));
        jbnInsertar.setText("INSERTAR");
        jbnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(jbnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 140, -1));

        jbnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jbnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnBuscar.setForeground(new java.awt.Color(51, 51, 51));
        jbnBuscar.setText("BUSCAR");
        jbnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 140, -1));

        jbnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jbnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jbnEliminar.setText("ELIMINAR");
        jbnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jbnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 140, -1));

        jbnPreOrden.setBackground(new java.awt.Color(204, 204, 204));
        jbnPreOrden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnPreOrden.setForeground(new java.awt.Color(51, 51, 51));
        jbnPreOrden.setText("PREORDEN");
        jbnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPreOrdenActionPerformed(evt);
            }
        });
        jPanel2.add(jbnPreOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 140, -1));

        jbnInOrden.setBackground(new java.awt.Color(204, 204, 204));
        jbnInOrden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnInOrden.setForeground(new java.awt.Color(51, 51, 51));
        jbnInOrden.setText("INORDEN");
        jbnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnInOrdenActionPerformed(evt);
            }
        });
        jPanel2.add(jbnInOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 140, -1));

        jbnPostOrden.setBackground(new java.awt.Color(204, 204, 204));
        jbnPostOrden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbnPostOrden.setForeground(new java.awt.Color(51, 51, 51));
        jbnPostOrden.setText("POSTORDEN");
        jbnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPostOrdenActionPerformed(evt);
            }
        });
        jPanel2.add(jbnPostOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("METODOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 850, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARBOL AVL GRAFICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPostOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.simulador.posOrden();
        this.jtaDatos.setText("");
        this.jtaDatos.setText(recorrido);
    }//GEN-LAST:event_jbnPostOrdenActionPerformed

    private void jbnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnInOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.simulador.inOrden();
        this.jtaDatos.setText("");
        this.jtaDatos.setText(recorrido);
    }//GEN-LAST:event_jbnInOrdenActionPerformed

    private void jbnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPreOrdenActionPerformed
        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.simulador.preOrden();
        this.jtaDatos.setText("");
        this.jtaDatos.setText(recorrido);

    }//GEN-LAST:event_jbnPreOrdenActionPerformed

    private void jbnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEliminarActionPerformed
        try {
            int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para borrar: "));
            this.jtaDatos.setText(this.simulador.borrar(dato));
            
            complementos();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbnEliminarActionPerformed

    private void jbnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnBuscarActionPerformed
        int dato_a_buscar = Integer.parseInt(JOptionPane.showInputDialog("Por favor digite un dato a buscar en el arbol:"));
        String salida = this.simulador.esta(dato_a_buscar);
        this.jtaDatos.setText("");
        this.jtaDatos.setText(salida);
    }//GEN-LAST:event_jbnBuscarActionPerformed

    private void jbnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnInsertarActionPerformed
        try {
            int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para insertar:"));
            if (this.simulador.insertar(dato)) {
                JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                this.inicializar(true);
                
                complementos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);
            
        }
    }//GEN-LAST:event_jbnInsertarActionPerformed
    
    public void complementos() {
        this.repintarArbol();
        
    }

    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        this.jInternalFrame2.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnBuscar;
    private javax.swing.JButton jbnEliminar;
    private javax.swing.JButton jbnInOrden;
    private javax.swing.JButton jbnInsertar;
    private javax.swing.JButton jbnPostOrden;
    private javax.swing.JButton jbnPreOrden;
    private javax.swing.JTextArea jtaDatos;
    // End of variables declaration//GEN-END:variables
}
